spring:
  application:
    name: Farragut
  main:
    banner-mode: LOG

server:
  port: 8060

security:
  authentication:
    jwt:
      # The secret should be 64 bytes (512 bits) long and must be encoded using Base64 (you can type `echo '<secret-key>' | base64` on your command line)
      # As this is the DEVELOPMENT configuration, a separate secret should be used in production, and stored securely:
      # - In a separate `application.yml` file, in the same folder as your executable WAR file
      secret: N1RnU21NM1hrbnBIN1ZMelQ5ZGJCWEp0VndIQVBoZGVtSHZiUEM1MnBXSzMzR3RuY1VOOTN0emJQWlFZRnR4cQo=
      token-validity-in-seconds: 14400 # Token is valid 4 hours
      token-validity-in-seconds-for-remember-me: 2592000 # Token is valid 30 days

logging:
  file:
    name: farragut.log
  level:
    # Start with only INFO messages
    root: INFO
    # Increase verbosity as needed
    org:
      avereon:
        farragut: INFO

