name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  JAVA_DISTRO: 'adopt'
  JAVA_VERSION: '21'
  MAVEN_PARMS: "-B -U -V --file pom.xml"

jobs:
  build:
    name: Compile, Test, Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          repository: avereon/farragut-api
          path: ..

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Compile
        run: |
          mvn ${{env.MAVEN_PARMS}} compile

      - name: Test
        run: |
          mvn ${{env.MAVEN_PARMS}} test

      - name: Analyze
        uses: github/codeql-action/analyze@v3
