name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
  AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
  AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
  AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}

  GITHUB_REF: ${{ github.ref }}
  JAVA_DISTRO: 'adopt'
  JAVA_VERSION: '17'
  MAVEN_PARMS: "-B -U -V --file pom.xml"

jobs:
  build:
    name: Compile, Test, Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Fetch CI/CD resources
        uses: actions/checkout@v4
        with:
          repository: avereon/canoe
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Compile
        run: |
          mvn ${{env.MAVEN_PARMS}} compile

      - name: Test
        run: |
          mvn ${{env.MAVEN_PARMS}} test

      - name: Analyze
        uses: github/codeql-action/analyze@v3

      - name: Test
        run: |
          mvn ${{env.MAVEN_PARMS}} -Dmaven.test.skip=true package

      - name: Copy Server JAR
        run: scp -B target/farragut-*.jar ${{env.AVN_REPO_USERNAME}}@avereon.com:/opt/avn/store/latest/farragut.avereon.com/server.jar

      - name: Update the Website
        run: ssh ${{env.AVN_REPO_USERNAME}}@avereon.com /home/ecco/bin/update-farragut-website
