name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  JAVA_DISTRO: 'adopt'
  JAVA_VERSION: '21'
  MAVEN_PARMS: "-B -U -V --file pom.xml"

jobs:
  build:
    name: Analyze, Compile, Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{env.JAVA_DISTRO}}
          java-version: ${{env.JAVA_VERSION}}

      - name: Compile
        working-directory: ./be
        run: |
          mvn ${{env.MAVEN_PARMS}} compile

      - name: Unit Tests
        working-directory: ./be
        run: |
          mvn ${{env.MAVEN_PARMS}} test
